python Busan.py
python Chungbuk.py
python Chungnam.py
python Daegu.py
python Daejeon.py
python Gangwon.py
python Gwangju.py
python Gyeongbuk.py
python Gyeonggi.py
python Gyeongnam.py
python Incheon.py
python Jeju.py
python Jeonbuk.py
python Jeonnam.py
python Sejong.py
python Seoul.py
python Ulsan.py